doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Packages\Club\Domain\Entity:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Packages/Club/Infrastructure/Mapping'
                prefix: 'App\Packages\Club\Domain\Entity'
                alias: Club
            App\Packages\Player\Domain\Entity:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Packages/Player/Infrastructure/Mapping'
                prefix: 'App\Packages\Player\Domain\Entity'
                alias: Player
            App\Packages\Coach\Domain\Entity:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Packages/Coach/Infrastructure/Mapping'
                prefix: 'App\Packages\Coach\Domain\Entity'
                alias: Coach

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
