App\Packages\Player\Domain\Entity\Value\PlayerName:
    type: embeddable
    fields:
        name:
            type: string
            scale: null
            length: 100
            unique: false
            nullable: false
            precision: null
        surname:
            type: string
            scale: null
            length: 200
            unique: false
            nullable: false
            precision: null