App\Packages\Coach\Domain\Entity\Coach:
    type: entity
    table: coach
    repositoryClass: App\Packages\Coach\Infrastructure\Persistence\Doctrine\CoachRepository
    id:
        id:
            type: uuid
            scale: null
            length: null
            unique: true
            nullable: false
            precision: null
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            scale: null
            length: 100
            unique: false
            nullable: false
            precision: null
        surname:
            type: string
            scale: null
            length: 200
            unique: false
            nullable: false
            precision: null
        yearOfBirth:
            type: integer
            scale: null
            length: null
            unique: false
            nullable: false
            precision: null
            column: year_of_birth
        city:
            type: string
            scale: null
            length: 100
            unique: false
            nullable: false
            precision: null
        country:
            type: string
            scale: null
            length: 100
            unique: false
            nullable: false
            precision: null
        salary:
            type: integer
            scale: null
            length: null
            unique: false
            nullable: false
            precision: null
        createdAt:
            type: datetime
            scale: null
            length: null
            unique: false
            nullable: false
            precision: null
            column: created_at
        updatedAt:
            type: datetime
            scale: null
            length: null
            unique: false
            nullable: true
            precision: null
            column: updated_at
    manyToOne:
        club:
            targetEntity: App\Packages\Club\Domain\Entity\Club
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: coaches
            joinColumns:
                club_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
