App\Packages\Coach\Domain\Entity\Coach:
    type: entity
    table: coach
    repositoryClass: App\Packages\Coach\Infrastructure\Persistence\Doctrine\CoachRepository
    fields:
        dateOfBirth:
            type: datetime
            scale: null
            length: null
            unique: false
            nullable: false
            precision: null
            column: date_of_birth
        createdAt:
            type: datetime_immutable
            scale: null
            length: null
            unique: false
            nullable: false
            precision: null
            column: created_at
            options:
                default: CURRENT_TIMESTAMP
        updatedAt:
            type: datetime_immutable
            scale: null
            length: null
            unique: false
            nullable: true
            precision: null
            column: updated_at
            columnDefinition: DATETIME on update CURRENT_TIMESTAMP
    embedded:
        id:
            class: App\Packages\Coach\Domain\Entity\Value\CoachUuid
            columnPrefix: false
        name:
            class: App\Packages\Coach\Domain\Entity\Value\CoachName
            columnPrefix: false
        city:
            class: App\Packages\Coach\Domain\Entity\Value\CoachCity
            columnPrefix: false
        country:
            class: App\Packages\Coach\Domain\Entity\Value\CoachCountry
            columnPrefix: false
        salary:
            class: App\Packages\Coach\Domain\Entity\Value\CoachSalary
            columnPrefix: false
        email:
            class: App\Packages\Coach\Domain\Entity\Value\CoachEmail
            columnPrefix: false
    manyToOne:
        club:
            targetEntity: App\Packages\Club\Domain\Entity\Club
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: coaches
            joinColumns:
                club_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
