App\Packages\Club\Domain\Entity\Club:
    type: entity
    table: club
    repositoryClass: App\Packages\Club\Infrastructure\Persistence\Doctrine\ClubRepository
    fields:
        createdAt:
            type: datetime_immutable
            scale: null
            length: null
            unique: false
            nullable: false
            precision: null
            column: created_at
            options:
                default: CURRENT_TIMESTAMP
        updatedAt:
            type: datetime_immutable
            scale: null
            length: null
            unique: false
            nullable: true
            precision: null
            column: updated_at
            columnDefinition: DATETIME DEFAULT NULL on update CURRENT_TIMESTAMP COMMENT '(DC2Type:datetime_immutable)'
    embedded:
        id:
            class: App\Packages\Club\Domain\Entity\Value\ClubUuid
            columnPrefix: false
        name:
            class: App\Packages\Club\Domain\Entity\Value\ClubName
            columnPrefix: false
        city:
            class: App\Packages\Club\Domain\Entity\Value\ClubCity
            columnPrefix: false
        country:
            class: App\Packages\Club\Domain\Entity\Value\ClubCountry
            columnPrefix: false
        budget:
            class: App\Packages\Club\Domain\Entity\Value\ClubBudget
            columnPrefix: false
    oneToMany:
        players:
            targetEntity: App\Packages\Player\Domain\Entity\Player
            cascade: {  }
            fetch: LAZY
            mappedBy: club
            inversedBy: null
            orphanRemoval: false
            orderBy: null
        coaches:
            targetEntity: App\Packages\Coach\Domain\Entity\Coach
            cascade: {  }
            fetch: LAZY
            mappedBy: club
            inversedBy: null
            orphanRemoval: false
            orderBy: null
    lifecycleCallbacks:
        prePersist: [ onPrePersist ]
        preUpdate: [ onPreUpdate ]